### ISSUE TITLE
4-4号博客那个2048游戏链接

### ISSUE THREAD

**Issue by guoyang1996** [ylxdzsw/ylxdzsw.github.io#1]
2048那个游戏的链接，点进去是当前博客的地址，链接还不能复制，只能手动敲。以及博客中，可以加个评论功能不

**Comment by ylxdzsw** [comment]
前几天起就编译不了了，大概哪个依赖包改了😂所以现在没法改。
评论稍微有点麻烦，有些帖子是编译好的HTML，还有一些是pdf。

**Comment by ylxdzsw** [comment]
修复了
